sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t ohad585/react-test -f ./client/Dockerfile.dev ./client 

script: 
 - docker run ohad585/react-test npm run test1

after_success: 
  - docker build -t ohad585/multi-client ./client
  - docker build -t ohad585/multi-nginx ./nginx
  - docker build -t ohad585/multi-server ./server
  - docker build -t ohad585/multi-worker ./worker
  #Log in to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Upload images
  - docker push ohad585/multi-client
  - docker push ohad585/multi-nginx
  - docker push ohad585/multi-server
  - docker push ohad585/multi-worker

 
